export interface IOrder {
    id: number,
    user_id: number,
    status: string,
    sub_total: number,
    item_discount: number,
    tax: number,
    shipping: number,
    total: number,
    promo: string,
    discount: number,
    grand_total: number,
    first_name: string,
    last_name: string,
    middle_name: string,
    mobile: string,
    email: string,
    commentary: string,
    address: string,
    city: string,
    region: string,
    country: string,
    content: string,
}