import { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
  await knex("product").del();

  await knex("product").insert([
    {
      user_id: 1,
      title: "product_1",
      meta_title: "product_1",
      slug: "product_1",
      sku: "123456",
      price: 1,
      discount: 0,
      quantity: 1,
      shop: 1,
      category_id: 9,
    },
    {
      user_id: 1,
      title: "product_2",
      meta_title: "product_2",
      slug: "product_2",
      sku: "223456",
      price: 1,
      discount: 0,
      quantity: 1,
      shop: 1,
      category_id: 9,
    },
    {
      user_id: 1,
      title: "product_3",
      meta_title: "product_3",
      slug: "product_3",
      sku: "323456",
      price: 1,
      discount: 0,
      quantity: 1,
      shop: 1,
      category_id: 9,
    },
    {
      user_id: 1,
      title: "product_4",
      meta_title: "product_4",
      slug: "product_4",
      sku: "423456",
      price: 1,
      discount: 0,
      quantity: 1,
      shop: 1,
      category_id: 9,
    },
    {
      user_id: 1,
      title: "product_5",
      meta_title: "product_5",
      slug: "product_5",
      sku: "523456",
      price: 1,
      discount: 0,
      quantity: 1,
      shop: 1,
      category_id: 9,
    },
    {
      user_id: 1,
      title: "product_6",
      meta_title: "product_6",
      slug: "product_6",
      sku: "623456",
      price: 1,
      discount: 0,
      quantity: 1,
      shop: 1,
      category_id: 9,
    },
    {
      user_id: 1,
      title: "product_7",
      meta_title: "product_7",
      slug: "product_7",
      sku: "723456",
      price: 1,
      discount: 0,
      quantity: 1,
      shop: 1,
      category_id: 9,
    },
    {
      user_id: 1,
      title: "product_8",
      meta_title: "product_8",
      slug: "product_8",
      sku: "823456",
      price: 1,
      discount: 0,
      quantity: 1,
      shop: 1,
      category_id: 9,
    },
    {
      user_id: 1,
      title: "product_9",
      meta_title: "product_9",
      slug: "product_9",
      sku: "923456",
      price: 1,
      discount: 0,
      quantity: 1,
      shop: 1,
      category_id: 9,
    },
  ]);
}
